# Generated by Django 6.0.7 on 2026-08-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImcApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='pessoa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ImcApp.pessoa'),
            preserve_default=False,
        ),
    ]
